<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Promissio.Benchmarks</AssemblyName>
    <RootNamespace>Promissio.Benchmarks</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../src/Promissio.Domain/Promissio.Domain.csproj" />
    <PackageReference Include="BenchmarkDotNet" />
  </ItemGroup>
</Project>
